---
- go on 5 dates
- pay off my debt
- build a website 
- quit smoking
- run a 10K
- write a short story
- raise $1K for charity
- learn to play hockey
- build a treehouse
- learn to knit
- quit coffee
- learn to play the guitar
- get an A+ in math
- floss daily
- paint a picture
- housetrain my puppy
- bake cookies
- practice yoga everyday
- quilt a blanket
- learn to massage 
- sew a costume
- stop drinking soda
- make a new friend
- get SCUBA certified
- fix my bike
- teach my son how ride a bike
- perform in an open mic
- lose 10 pounds
- build a kayak
- get certified in CPR
- organize a family reunion
- journal everyday
- get my tattoos removed
- benchpress 100lbs
- plan a Vegas bachelors party
- design a mobile app
- earn $1K for charity
- hike 5 new trails
- learn to tap dance
- visit 5 cities
- clean out my basement
- grow a garden
- hit a bullseye at darts